(ns fulcro-template.locales.es (:require fulcro.i18n))

;; This file was generated by untangled's i18n leiningen plugin.

(def
 translations
 {"|Please supply your name.`" "Por favor suministre su nombre.'",
  "|Password" "Contraseña",
  "|Password must be at least 7 characters long"
  "La contraseña debe contener al menos 7 caracteres",
  "|Email Address" "Dirección de correo electrónico",
  "|Passwords must match" "Las contraseñas deben coincidir",
  "|Email" "Email",
  "|Must be a valid email address.`"
  "Debe ser una dirección de correo electrónico válida.",
  "|A server error happened. Please try again."
  "Ocurrió un error de servidor. Por favor, inténtelo de nuevo.",
  "|Sign Up!" "¡Registrarse!",
  "|Name" "Nombre",
  "|Verify Password" "Verificar Contraseña"})

(swap! fulcro.i18n/*loaded-translations* assoc :es translations)